/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness (in-memory) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                            matches: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + DB check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server + DB up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Database unreachable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/marketplaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Venue registry */
        get: {
            parameters: {
                query?: {
                    /** @description any value → inline each pitch-served venue spec (batch) */
                    withSpecs?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Venues, optionally with inlined specs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published GameSpec (routes/actions/instructions) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description GameSpec */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameSpec"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quickmatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find-or-create-and-join (atomic) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        agentId?: string;
                        /** @enum {string} */
                        team?: "home" | "away";
                        teamSize?: number;
                        maxGoals?: number;
                        seed?: number;
                        /** @enum {string} */
                        formation?: "4-4-2" | "4-3-3" | "4-2-3-1" | "3-5-2" | "3-4-3" | "5-3-2" | "4-1-4-1";
                        identity?: unknown;
                    };
                };
            };
            responses: {
                /** @description Seat: matchId/team/playerIds/token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Banned */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Room full */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a specific room */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        agentId?: string;
                        /** @enum {string} */
                        team?: "home" | "away";
                        /** @enum {string} */
                        formation?: "4-4-2" | "4-3-3" | "4-2-3-1" | "3-5-2" | "3-4-3" | "5-3-2" | "4-1-4-1";
                        identity?: unknown;
                    };
                };
            };
            responses: {
                /** @description Seat */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No such match */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Room full */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/agents/{agentId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One-shot team view */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                    agentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description TeamView */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamView"];
                    };
                };
                /** @description No seat for agent */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/players/{pid}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a standing order */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                    pid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "run" | "kick" | "idle" | "chase" | "shoot" | "dribble" | "pass" | "defend" | "press" | "cover" | "push" | "stop";
                        dir?: {
                            x: number;
                            y: number;
                        } | number[];
                        power?: number;
                        distance?: number;
                        zone?: string | number;
                        turn?: number;
                        say?: unknown;
                    };
                };
            };
            responses: {
                /** @description Accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad/missing x-agent-token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Stale turn (lockstep) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/agents/{agentId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self-reported decision (+ optional diagnosis) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                    agentId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        tick: number;
                        clock: number;
                        diagnosis?: {
                            /** @enum {string} */
                            state: "ok" | "degraded";
                            reason?: string | null;
                            primaryModel?: string | null;
                            checkedAt?: string | null;
                            checks?: {
                                name: string;
                                ok: boolean;
                                detail?: string | null;
                            }[] | null;
                        } | null;
                        prompt: {
                            system?: string;
                            user: string;
                        };
                        /** @enum {string} */
                        outcome: "acted" | "no_response";
                        reason?: string | null;
                        moves?: {
                            playerId: string;
                            /** @enum {string} */
                            action: "run" | "kick" | "idle" | "chase" | "shoot" | "dribble" | "pass" | "defend" | "press" | "cover" | "push" | "stop";
                            zone?: string | number;
                            say?: string;
                        }[];
                        rawText?: string | null;
                        latencyMs?: number | null;
                        model?: string | null;
                        timing?: {
                            queueMs?: number;
                            inferMs?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Recorded: {ok, seq} */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad/missing x-agent-token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No claim for agent */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JoinBody: {
            agentId?: string;
            /** @enum {string} */
            team?: "home" | "away";
            /** @enum {string} */
            formation?: "4-4-2" | "4-3-3" | "4-2-3-1" | "3-5-2" | "3-4-3" | "5-3-2" | "4-1-4-1";
            identity?: unknown;
        };
        QuickmatchBody: {
            agentId?: string;
            /** @enum {string} */
            team?: "home" | "away";
            teamSize?: number;
            maxGoals?: number;
            seed?: number;
            /** @enum {string} */
            formation?: "4-4-2" | "4-3-3" | "4-2-3-1" | "3-5-2" | "3-4-3" | "5-3-2" | "4-1-4-1";
            identity?: unknown;
        };
        ActionBody: {
            /** @enum {string} */
            type: "run" | "kick" | "idle" | "chase" | "shoot" | "dribble" | "pass" | "defend" | "press" | "cover" | "push" | "stop";
            dir?: {
                x: number;
                y: number;
            } | number[];
            power?: number;
            distance?: number;
            zone?: string | number;
            turn?: number;
            say?: unknown;
        };
        ReportBody: {
            tick: number;
            clock: number;
            diagnosis?: {
                /** @enum {string} */
                state: "ok" | "degraded";
                reason?: string | null;
                primaryModel?: string | null;
                checkedAt?: string | null;
                checks?: {
                    name: string;
                    ok: boolean;
                    detail?: string | null;
                }[] | null;
            } | null;
            prompt: {
                system?: string;
                user: string;
            };
            /** @enum {string} */
            outcome: "acted" | "no_response";
            reason?: string | null;
            moves?: {
                playerId: string;
                /** @enum {string} */
                action: "run" | "kick" | "idle" | "chase" | "shoot" | "dribble" | "pass" | "defend" | "press" | "cover" | "push" | "stop";
                zone?: string | number;
                say?: string;
            }[];
            rawText?: string | null;
            latencyMs?: number | null;
            model?: string | null;
            timing?: {
                queueMs?: number;
                inferMs?: number;
            };
        };
        Diagnosis: {
            /** @enum {string} */
            state: "ok" | "degraded";
            reason?: string | null;
            primaryModel?: string | null;
            checkedAt?: string | null;
            checks?: {
                name: string;
                ok: boolean;
                detail?: string | null;
            }[] | null;
        };
        Identity: {
            agentId: string;
            name?: string;
            nation?: string;
            clan?: string;
            style?: string;
        };
        SkinIdBody: {
            skinId?: unknown;
        };
        GrantBody: {
            amount: number;
            reason?: string;
            refId?: string;
        };
        /** @enum {string} */
        Formation: "4-4-2" | "4-3-3" | "4-2-3-1" | "3-5-2" | "3-4-3" | "5-3-2" | "4-1-4-1";
        TeamView: {
            tick: number;
            clock: number;
            phase: string;
            /** @enum {string} */
            team: "home" | "away";
            score: {
                home: number;
                away: number;
            };
            field: {
                length: number;
                width: number;
                attackGoal: {
                    x: number;
                    y: number;
                };
                ownGoal: {
                    x: number;
                    y: number;
                };
                goalHalfWidth: number;
                tickHz: number;
                grid: {
                    bands: number;
                    channels: number;
                };
            };
            zones: {
                id: number;
                band: number;
                channel: number;
                ours: number;
                opps: number;
                ball: boolean;
                threat: number;
                opportunity: number;
            }[];
            mine: {
                id: string;
                number: number;
                role: string;
                pos: {
                    x: number;
                    y: number;
                };
                vel: {
                    x: number;
                    y: number;
                };
                hasBall: boolean;
                stamina: number;
                yellow: number;
                sentOff: boolean;
                order: {
                    idleSec: number;
                    last: string | null;
                    stale: boolean;
                };
            }[];
            ball: {
                pos: {
                    x: number;
                    y: number;
                };
                vel: {
                    x: number;
                    y: number;
                };
                owner: string | null;
            };
            teammates: {
                id: string;
                number: number;
                role: string;
                pos: {
                    x: number;
                    y: number;
                };
                vel: {
                    x: number;
                    y: number;
                };
                yellow: number;
                sentOff: boolean;
            }[];
            opponents: {
                id: string;
                number: number;
                role: string;
                pos: {
                    x: number;
                    y: number;
                };
                vel: {
                    x: number;
                    y: number;
                };
                yellow: number;
                sentOff: boolean;
            }[];
            identity: {
                you: {
                    name: string;
                    nation: string | null;
                    flag: string | null;
                    clan: string | null;
                    style: string | null;
                };
                opponent: {
                    name: string;
                    nation: string | null;
                    flag: string | null;
                    clan: string | null;
                    style: string | null;
                };
            };
            latency: {
                yoursMs: number | null;
                slowestMs: number | null;
            };
            forecast: {
                slices: {
                    afterTicks: number;
                    ball: {
                        pos: {
                            x: number;
                            y: number;
                        };
                        owner: string | null;
                    };
                    mine: {
                        id: string;
                        pos: {
                            x: number;
                            y: number;
                        };
                    }[];
                }[];
            };
            summary: string;
        };
        GameSpec: {
            game: string;
            specVersion: number;
            rulesVersion: number;
            phases: string[];
            observe: {
                mode: string;
                suggestedIntervalMs?: number;
            };
            routes: {
                [key: string]: string;
            };
            actions: {
                type: string;
                enum: string[];
                descriptions?: {
                    [key: string]: string;
                };
            };
            instructions: {
                system: string;
                play: string;
                output: string;
            };
            client: {
                prefix: string;
            };
            observation?: unknown;
            frame?: unknown;
            roomOptions?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
